/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchInput = IDL.Record({
  'date' : IDL.Text,
  'time' : IDL.Text,
  'place' : IDL.Text,
  'maxPlayers' : IDL.Nat,
});
export const PlayerInput = IDL.Record({
  'nickname' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'position' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const PlayerId = IDL.Nat;
export const ConfirmedPlayer = IDL.Record({
  'nickname' : IDL.Text,
  'playerId' : PlayerId,
  'name' : IDL.Text,
  'position' : IDL.Text,
});
export const MatchId = IDL.Nat;
export const AttendanceSummary = IDL.Record({
  'pending' : IDL.Vec(ConfirmedPlayer),
  'matchId' : MatchId,
  'spotsLeft' : IDL.Nat,
  'confirmed' : IDL.Vec(ConfirmedPlayer),
  'declined' : IDL.Vec(ConfirmedPlayer),
});
export const Timestamp = IDL.Int;
export const MatchView = IDL.Record({
  'id' : MatchId,
  'cancelled' : IDL.Bool,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'place' : IDL.Text,
  'maxPlayers' : IDL.Nat,
});
export const PlayerView = IDL.Record({
  'id' : PlayerId,
  'nickname' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'phone' : IDL.Text,
  'position' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'confirmed' : IDL.Null,
  'declined' : IDL.Null,
});
export const AttendanceView = IDL.Record({
  'status' : AttendanceStatus,
  'playerId' : PlayerId,
  'updatedAt' : Timestamp,
  'matchId' : MatchId,
});
export const MatchResultView = IDL.Record({
  'teamA' : IDL.Vec(PlayerId),
  'teamB' : IDL.Vec(PlayerId),
  'recordedAt' : Timestamp,
  'matchId' : MatchId,
  'goalsTeamA' : IDL.Nat,
  'goalsTeamB' : IDL.Nat,
});
export const MatchHistoryEntry = IDL.Record({
  'match' : MatchView,
  'result' : IDL.Opt(MatchResultView),
  'players' : IDL.Vec(PlayerId),
});
export const MatchResultInput = IDL.Record({
  'teamA' : IDL.Vec(PlayerId),
  'teamB' : IDL.Vec(PlayerId),
  'goalsTeamA' : IDL.Nat,
  'goalsTeamB' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelMatch' : IDL.Func([IDL.Nat], [], []),
  'createMatch' : IDL.Func([MatchInput], [IDL.Nat], []),
  'createPlayer' : IDL.Func([PlayerInput], [IDL.Nat], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAttendanceSummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AttendanceSummary)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(MatchView)], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(PlayerView)], ['query']),
  'getPlayerAttendance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceView)],
      ['query'],
    ),
  'getResult' : IDL.Func([IDL.Nat], [IDL.Opt(MatchResultView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
  'listHistory' : IDL.Func([], [IDL.Vec(MatchHistoryEntry)], ['query']),
  'listPlayers' : IDL.Func([], [IDL.Vec(PlayerView)], ['query']),
  'listUpcomingMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
  'recordResult' : IDL.Func([IDL.Nat, MatchResultInput], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchPlayers' : IDL.Func([IDL.Text], [IDL.Vec(PlayerView)], ['query']),
  'setAttendance' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'updateMatch' : IDL.Func([IDL.Nat, MatchInput], [], []),
  'updatePlayer' : IDL.Func([IDL.Nat, PlayerInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchInput = IDL.Record({
    'date' : IDL.Text,
    'time' : IDL.Text,
    'place' : IDL.Text,
    'maxPlayers' : IDL.Nat,
  });
  const PlayerInput = IDL.Record({
    'nickname' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'position' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const PlayerId = IDL.Nat;
  const ConfirmedPlayer = IDL.Record({
    'nickname' : IDL.Text,
    'playerId' : PlayerId,
    'name' : IDL.Text,
    'position' : IDL.Text,
  });
  const MatchId = IDL.Nat;
  const AttendanceSummary = IDL.Record({
    'pending' : IDL.Vec(ConfirmedPlayer),
    'matchId' : MatchId,
    'spotsLeft' : IDL.Nat,
    'confirmed' : IDL.Vec(ConfirmedPlayer),
    'declined' : IDL.Vec(ConfirmedPlayer),
  });
  const Timestamp = IDL.Int;
  const MatchView = IDL.Record({
    'id' : MatchId,
    'cancelled' : IDL.Bool,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'place' : IDL.Text,
    'maxPlayers' : IDL.Nat,
  });
  const PlayerView = IDL.Record({
    'id' : PlayerId,
    'nickname' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'phone' : IDL.Text,
    'position' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'confirmed' : IDL.Null,
    'declined' : IDL.Null,
  });
  const AttendanceView = IDL.Record({
    'status' : AttendanceStatus,
    'playerId' : PlayerId,
    'updatedAt' : Timestamp,
    'matchId' : MatchId,
  });
  const MatchResultView = IDL.Record({
    'teamA' : IDL.Vec(PlayerId),
    'teamB' : IDL.Vec(PlayerId),
    'recordedAt' : Timestamp,
    'matchId' : MatchId,
    'goalsTeamA' : IDL.Nat,
    'goalsTeamB' : IDL.Nat,
  });
  const MatchHistoryEntry = IDL.Record({
    'match' : MatchView,
    'result' : IDL.Opt(MatchResultView),
    'players' : IDL.Vec(PlayerId),
  });
  const MatchResultInput = IDL.Record({
    'teamA' : IDL.Vec(PlayerId),
    'teamB' : IDL.Vec(PlayerId),
    'goalsTeamA' : IDL.Nat,
    'goalsTeamB' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelMatch' : IDL.Func([IDL.Nat], [], []),
    'createMatch' : IDL.Func([MatchInput], [IDL.Nat], []),
    'createPlayer' : IDL.Func([PlayerInput], [IDL.Nat], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAttendanceSummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AttendanceSummary)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(MatchView)], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(PlayerView)], ['query']),
    'getPlayerAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceView)],
        ['query'],
      ),
    'getResult' : IDL.Func([IDL.Nat], [IDL.Opt(MatchResultView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
    'listHistory' : IDL.Func([], [IDL.Vec(MatchHistoryEntry)], ['query']),
    'listPlayers' : IDL.Func([], [IDL.Vec(PlayerView)], ['query']),
    'listUpcomingMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
    'recordResult' : IDL.Func([IDL.Nat, MatchResultInput], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchPlayers' : IDL.Func([IDL.Text], [IDL.Vec(PlayerView)], ['query']),
    'setAttendance' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'updateMatch' : IDL.Func([IDL.Nat, MatchInput], [], []),
    'updatePlayer' : IDL.Func([IDL.Nat, PlayerInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };