/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttendanceStatus = { 'confirmed' : null } |
  { 'declined' : null };
export interface AttendanceSummary {
  'pending' : Array<ConfirmedPlayer>,
  'matchId' : MatchId,
  'spotsLeft' : bigint,
  'confirmed' : Array<ConfirmedPlayer>,
  'declined' : Array<ConfirmedPlayer>,
}
export interface AttendanceView {
  'status' : AttendanceStatus,
  'playerId' : PlayerId,
  'updatedAt' : Timestamp,
  'matchId' : MatchId,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ConfirmedPlayer {
  'nickname' : string,
  'playerId' : PlayerId,
  'name' : string,
  'position' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface MatchHistoryEntry {
  'match' : MatchView,
  'result' : [] | [MatchResultView],
  'players' : Array<PlayerId>,
}
export type MatchId = bigint;
export interface MatchInput {
  'date' : string,
  'time' : string,
  'place' : string,
  'maxPlayers' : bigint,
}
export interface MatchResultInput {
  'teamA' : Array<PlayerId>,
  'teamB' : Array<PlayerId>,
  'goalsTeamA' : bigint,
  'goalsTeamB' : bigint,
}
export interface MatchResultView {
  'teamA' : Array<PlayerId>,
  'teamB' : Array<PlayerId>,
  'recordedAt' : Timestamp,
  'matchId' : MatchId,
  'goalsTeamA' : bigint,
  'goalsTeamB' : bigint,
}
export interface MatchView {
  'id' : MatchId,
  'cancelled' : boolean,
  'date' : string,
  'createdAt' : Timestamp,
  'time' : string,
  'place' : string,
  'maxPlayers' : bigint,
}
export type PlayerId = bigint;
export interface PlayerInput {
  'nickname' : string,
  'name' : string,
  'phone' : string,
  'position' : string,
}
export interface PlayerView {
  'id' : PlayerId,
  'nickname' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'phone' : string,
  'position' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Cancels a match. Organizer only.
   */
  'cancelMatch' : ActorMethod<[bigint], undefined>,
  /**
   * / Creates a match. Organizer only.
   */
  'createMatch' : ActorMethod<[MatchInput], bigint>,
  /**
   * / Creates a player. Organizer only.
   */
  'createPlayer' : ActorMethod<[PlayerInput], bigint>,
  /**
   * / Removes a player. Organizer only.
   */
  'deletePlayer' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Returns the backend API documentation as static Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Returns the live attendance summary for a match.
   */
  'getAttendanceSummary' : ActorMethod<[bigint], [] | [AttendanceSummary]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns one match by id.
   */
  'getMatch' : ActorMethod<[bigint], [] | [MatchView]>,
  /**
   * / Returns one player by id.
   */
  'getPlayer' : ActorMethod<[bigint], [] | [PlayerView]>,
  /**
   * / Returns the attendance history of one player.
   */
  'getPlayerAttendance' : ActorMethod<[bigint], Array<AttendanceView>>,
  /**
   * / Returns the recorded result of a match.
   */
  'getResult' : ActorMethod<[bigint], [] | [MatchResultView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Lists every match, including cancelled ones.
   */
  'listAllMatches' : ActorMethod<[], Array<MatchView>>,
  /**
   * / Returns past matches with their result and participants.
   */
  'listHistory' : ActorMethod<[], Array<MatchHistoryEntry>>,
  /**
   * / Lists every player in the roster.
   */
  'listPlayers' : ActorMethod<[], Array<PlayerView>>,
  /**
   * / Lists upcoming matches ordered by date.
   */
  'listUpcomingMatches' : ActorMethod<[], Array<MatchView>>,
  /**
   * / Records the final result and line-ups of a played match. Organizer only.
   */
  'recordResult' : ActorMethod<[bigint, MatchResultInput], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Searches the roster by name or nickname.
   */
  'searchPlayers' : ActorMethod<[string], Array<PlayerView>>,
  /**
   * / Confirms or declines the caller's attendance to a match.
   */
  'setAttendance' : ActorMethod<[bigint, bigint, boolean], undefined>,
  /**
   * / Updates a match. Organizer only.
   */
  'updateMatch' : ActorMethod<[bigint, MatchInput], undefined>,
  /**
   * / Updates a player. Organizer only.
   */
  'updatePlayer' : ActorMethod<[bigint, PlayerInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];